/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as finance from "./finance";
export type { finance };
import type * as realEstate from "./realEstate";
export type { realEstate };
import type * as supplyChain from "./supplyChain";
export type { supplyChain };
