/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfacesSol from "./Interfaces.sol";
export type { interfacesSol };
export type { AutomatedProcess } from "./AutomatedProcess";
export type { InventoryManagement } from "./InventoryManagement";
export type { Provenance } from "./Provenance";
