/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfacesSol from "./Interfaces.sol";
export { AutomatedProcess__factory } from "./AutomatedProcess__factory";
export { InventoryManagement__factory } from "./InventoryManagement__factory";
export { Provenance__factory } from "./Provenance__factory";
