/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAutomatedProcess } from "./IAutomatedProcess";
export type { IInventoryManagement } from "./IInventoryManagement";
export type { IProvenance } from "./IProvenance";
