/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAutomatedProcess,
  IAutomatedProcessInterface,
} from "../../../../contracts/supplyChain/Interfaces.sol/IAutomatedProcess";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "setProcessValue",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IAutomatedProcess__factory {
  static readonly abi = _abi;
  static createInterface(): IAutomatedProcessInterface {
    return new utils.Interface(_abi) as IAutomatedProcessInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAutomatedProcess {
    return new Contract(address, _abi, signerOrProvider) as IAutomatedProcess;
  }
}
