/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAutomatedProcess__factory } from "./IAutomatedProcess__factory";
export { IInventoryManagement__factory } from "./IInventoryManagement__factory";
export { IProvenance__factory } from "./IProvenance__factory";
