/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProvenance,
  IProvenanceInterface,
} from "../../../../contracts/supplyChain/Interfaces.sol/IProvenance";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_productId",
        type: "bytes",
      },
    ],
    name: "isCompleted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProvenance__factory {
  static readonly abi = _abi;
  static createInterface(): IProvenanceInterface {
    return new utils.Interface(_abi) as IProvenanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProvenance {
    return new Contract(address, _abi, signerOrProvider) as IProvenance;
  }
}
